name: Security Scan

on:
  push:
    branches:
      - main  # Change this to your default branch name, if different

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Run Semgrep
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          args: --config=p/security-audit

      # Step 3: Run Nuclei
      - name: Install Nuclei
        run: |
          # Download and install nuclei
          curl -sL https://raw.githubusercontent.com/projectdiscovery/nuclei/master/install.sh | bash
      - name: Run Nuclei
        run: nuclei -update-templates && nuclei -t cves/ -severity high,medium,low -u https://yourwebsite.com

